test_horizon: 50
lr: 0.001
x_dim: 1
y_dim: 1
sigma_eps: 0.05

data_horizon: 50
meta_batch_size: 40

nn_layers: [128,128,128]
activation: 'tanh'

# step params:
step_min: -2.5
step_max: 2.5
x_range: [-5., 5.]
num_steps: 3
