test_horizon: 10
lr: 0.001
x_dim: 3 
y_dim: 2
sigma_eps: 0.001

data_horizon: 20
meta_batch_size: 20

nn_layers: [128,128,16]
activation: 'tanh'

# pendulum params:
pendulum_mass_min: 0.5
pendulum_mass_max: 1.5

pendulum_len_min: 0.5
pendulum_len_max: 1.5