lr: 0.001
x_dim: 1
y_dim: 1
sigma_eps: 0.02

data_horizon: 10
test_horizon: 20
meta_batch_size: 10

nn_layers: [128,128, 32]
activation: 'tanh'

# sinusoid params:
phase_range: [0, 3.14]
freq_range: [0.999, 1.0]
amp_range: [0.1, 5.0]
x_range: [-5., 5.]
noise_var: 0.02
